// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvjO7mw_aaGRIiK0tc4Vj_JAOdTmoRJmk',
    appId: '1:602122237044:web:111144c185fdd06c288d21',
    messagingSenderId: '602122237044',
    projectId: 'learn-firebase-auth-fc20e',
    authDomain: 'learn-firebase-auth-fc20e.firebaseapp.com',
    storageBucket: 'learn-firebase-auth-fc20e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMstOntFLI_EsZ9OVghvt1ixnKw0S9k18',
    appId: '1:602122237044:android:4dda05751af7a22a288d21',
    messagingSenderId: '602122237044',
    projectId: 'learn-firebase-auth-fc20e',
    storageBucket: 'learn-firebase-auth-fc20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2LWd6Q7exlFCcaWJnNOUALPC4tVUeYrM',
    appId: '1:602122237044:ios:9581b1c84be9a265288d21',
    messagingSenderId: '602122237044',
    projectId: 'learn-firebase-auth-fc20e',
    storageBucket: 'learn-firebase-auth-fc20e.appspot.com',
    iosBundleId: 'com.example.learnFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2LWd6Q7exlFCcaWJnNOUALPC4tVUeYrM',
    appId: '1:602122237044:ios:9581b1c84be9a265288d21',
    messagingSenderId: '602122237044',
    projectId: 'learn-firebase-auth-fc20e',
    storageBucket: 'learn-firebase-auth-fc20e.appspot.com',
    iosBundleId: 'com.example.learnFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvjO7mw_aaGRIiK0tc4Vj_JAOdTmoRJmk',
    appId: '1:602122237044:web:084a050de7e5b184288d21',
    messagingSenderId: '602122237044',
    projectId: 'learn-firebase-auth-fc20e',
    authDomain: 'learn-firebase-auth-fc20e.firebaseapp.com',
    storageBucket: 'learn-firebase-auth-fc20e.appspot.com',
  );
}
